# Permalinks
permalink:           pretty

# Setup
title:               Digests
tagline:             d4n13l
url:                 http://getpoole.com
paginate:            3
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Daniel Zhenikhiv
  url:               https://vk.com/itecn
  email:             zhe.dan28@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/daniel5541/test-akka-with-kafka

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

theme: jekyll-theme-cayman
